# fly.toml app configuration file generated for fs-board-and-admin-deploy on 2024-02-21T21:47:04+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fs-board-and-admin-deploy'
primary_region = 'nrt'

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
